name: Test Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Minimal Python heredoc test
        run: |
          python3 - <<'PY'
print("Hei fra Python!")
PY
